### ISSUE TITLE
想请教下大佬如何在特定的位置下插入latex公式？

### ISSUE THREAD

**Issue by cfx843010518** [draco1023/poi-tl-ext#10]
我看了你的源码，发现是对paragraph.getCTP().addNewOMath()的调用往word里面写入数学公式，但是这样会导致一个问题，导致了在当前段落的最后面进行写入了，导致现在一个情况。公式写进去以后跑到了最后面了
![image](https://user-images.githubusercontent.com/28293057/122649505-a75eb700-d160-11eb-8cc6-4853d77214ac.png)
![image](https://user-images.githubusercontent.com/28293057/122649559-f3a9f700-d160-11eb-95cb-7cf9e35fece2.png)
我自己试了好久POI的api发现都没法改变位置，大佬能指点一下吗。感谢感谢！！！

**Comment by draco1023** [comment]
@cfx843010518 请提供下模板文档

**Comment by cfx843010518** [comment]
可以的。
[template.docx](https://github.com/draco1023/poi-tl-ext/files/6685343/template.docx)
公式案例：$$f\left( x\right)=\frac{x}{x+1}+\frac{x+1}{x+2}+\frac{x+2}{x+3}$$
实现的效果应该是在title的位置进行替换。
不过这个我发现了一个解决办法，只要重写addMath方法，设置进当前块的run对象里面，就能实现在特定的位置渲染。
![image](https://user-images.githubusercontent.com/28293057/122735462-a38e7a00-d2b1-11eb-98eb-3046a5691703.png)

**Comment by cfx843010518** [comment]
还有能再提个意见吗，我这边一般很少说单独某个富文本或者公式渲染的，通常一个占位符，可能对应（富文本+公式）的情况，大佬能把两者结合起来，写个两者综合的处理器吗。蟹蟹大佬！！！

**Comment by draco1023** [comment]
富文本里的公式一般都是使用MathML标记，没有直接嵌入 LaTex 的，二者是不同的标记语法，现在的富文本渲染本身就已经包含了对 MathML 的处理。

**Comment by draco1023** [comment]
> 可以的。
> [template.docx](https://github.com/draco1023/poi-tl-ext/files/6685343/template.docx)
> 公式案例：$$f\left( x\right)=\frac{x}{x+1}+\frac{x+1}{x+2}+\frac{x+2}{x+3}$$
> 实现的效果应该是在title的位置进行替换。
> 不过这个我发现了一个解决办法，只要重写addMath方法，设置进当前块的run对象里面，就能实现在特定的位置渲染。
> ![image](https://user-images.githubusercontent.com/28293057/122735462-a38e7a00-d2b1-11eb-98eb-3046a5691703.png)

这种直接获取CTR设置的方式，只能对单独的MathML或者单独的LaTex生效，会导致包含公式的富文本输出错误的数据。

**Comment by cfx843010518** [comment]
> 富文本里的公式一般都是使用MathML标记，没有直接嵌入 LaTex 的，二者是不同的标记语法，现在的富文本渲染本身就已经包含了对 MathML 的处理。

确实可以了强无敌呀。

**Comment by cfx843010518** [comment]
大佬，富文本的写入也会有那个占位问题，例如 我的模板，我想在中间写入富文本，但是写完以后，跑到后面去了，我debug源码发现都是在段落（XWPFParagraph）对象通过createRun来进行写入，那不是变成追加了吗？如何在指定的位置写入呢？
写之前 ： [template.docx](https://github.com/draco1023/poi-tl-ext/files/6686562/template.docx)
写之后：[template.docx](https://github.com/draco1023/poi-tl-ext/files/6686563/template.docx)

**Comment by draco1023** [comment]
> 大佬，富文本的写入也会有那个占位问题，例如 我的模板，我想在中间写入富文本，但是写完以后，跑到后面去了，我debug源码发现都是在段落（XWPFParagraph）对象通过createRun来进行写入，那不是变成追加了吗？如何在指定的位置写入呢？
> 写之前 ： [template.docx](https://github.com/draco1023/poi-tl-ext/files/6686562/template.docx)
> 写之后：[template.docx](https://github.com/draco1023/poi-tl-ext/files/6686563/template.docx)

我认为这是 poi-tl 本身对于模板处理逻辑上问题，而不是某一种渲染策略的问题。不过你可以将那些前后拼接的固定字符串拼接到模板变量的内容中，整体只使用一个变量是没问题的。

**Comment by cfx843010518** [comment]
> > 大佬，富文本的写入也会有那个占位问题，例如 我的模板，我想在中间写入富文本，但是写完以后，跑到后面去了，我debug源码发现都是在段落（XWPFParagraph）对象通过createRun来进行写入，那不是变成追加了吗？如何在指定的位置写入呢？
> > 写之前 ： [template.docx](https://github.com/draco1023/poi-tl-ext/files/6686562/template.docx)
> > 写之后：[template.docx](https://github.com/draco1023/poi-tl-ext/files/6686563/template.docx)
> 
> 我怀疑这是 poi-tl 本身对于模板处理逻辑上的问题，而不是某一种渲染策略的问题。不过你可以将那些前后拼接的固定字符串拼接到模板变量的内容中，整体只使用一个变量是没问题的。
> 我会再看看如何处理更好

好的，感谢大佬。

**Comment by draco1023** [comment]
关于渲染位置的问题，已经解决了公式的（在dev分支提交了最新代码），但是对于富文本会相对复杂，如果富文本中仅仅包含行内元素，是可以按照与公式类似的方法解决，但是如果存在块状元素是需要另起一个段落的，需要破坏占位符所在的段落结构。

**Comment by cfx843010518** [comment]
> 关于渲染位置的问题，已经解决了公式的（在dev分支提交了最新代码），但是对于富文本会相对复杂，如果富文本中仅仅包含行内元素，是可以按照与公式类似的方法解决，但是如果存在块状元素是需要另起一个段落的，需要破坏占位符所在的段落结构。

哇塞，牛逼。点赞点赞。

**Comment by cfx843010518** [comment]
<p><span style="margin:0px 50px 0px 0px;">A：答案1</span><span style="margin:0px 50px 0px 0px;">B：答案1</span><span style="margin:0px 50px 0px 0px;">C：答案1</span></p> 为什么这种间隔的样式没法渲染出来？
出来的效果还是连在一起   A：答案1B：答案1C：答案1

**Comment by cfx843010518** [comment]
A : 答案1&nbsp; &nbsp; &nbsp;B<span>&nbsp;: 答案1&nbsp; &nbsp; C<span>&nbsp;: 答案2&nbsp; &nbsp; D<span>&nbsp;: 答案D</span></span></span>
为什么这种格式没法渲染出来呢，我只是想把选项排开，求解

**Comment by draco1023** [comment]
> A : 答案1     B : 答案1    C : 答案2    D : 答案D
> [word.txt](https://github.com/draco1023/poi-tl-ext/files/6693257/word.txt)
> 为什么这种格式没法渲染出来呢，我只是想把答案选项排开，求大佬解答！！！

![image](https://user-images.githubusercontent.com/1821583/122919895-584c9800-d393-11eb-9e75-65019a7fd5e8.png)
不是可以渲染出来吗？

如果你的意思是空格数量不对，那确实是的，影响的代码如下：

https://github.com/draco1023/poi-tl-ext/blob/38b0a543731427e39e38e442758fc41973c42d14/src/main/java/org/ddr/poi/html/HtmlRenderPolicy.java#L158

通常来讲通过空格来控制间距不是个好主意，如果你一定要这样做，可以把上面那行的 text() 改成 getWholeText()，但是这样仍然存在问题，\&nbsp; 之间的空格也会被算作空格，因此答案1和B之间会有5个空格。

**Comment by cfx843010518** [comment]
<p><span style="margin:0px 50px 0px 0px;">A：答案1</span><span style="margin:0px 50px 0px 0px;">B：答案1</span><span style="margin:0px 50px 0px 0px;">C：答案1</span></p>

**Comment by draco1023** [comment]
> 不知道为什么这样写也不行
> [word.txt](https://github.com/draco1023/poi-tl-ext/files/6694488/word.txt)

行内元素使用margin或者padding在word中没有对应的样式来控制。你可以仔细看下text() 方法的实现，其实是对 getWholeText() 进行了一次字符拼接，把首尾的多个空白字符限制为最多一个，这里可以按需自定义。

**Comment by cfx843010518** [comment]
> > 不知道为什么这样写也不行
> > [word.txt](https://github.com/draco1023/poi-tl-ext/files/6694488/word.txt)
> 
> 行内元素使用margin或者padding在word中没有对应的样式来控制。你可以仔细看下text() 方法的实现，其实是对 getWholeText() 进行了一次字符拼接，把首尾的多个空白字符限制为最多一个，这里可以按需自定义。

好的，这几天也看了好多，奈何水平不够，有些地方看不懂，你是对着apache poi的那个api文档（http://poi.apache.org/apidocs/4.1/）硬撸的吗，想请教下还有什么这方面的文档

**Comment by draco1023** [comment]
> > > 不知道为什么这样写也不行
> > > [word.txt](https://github.com/draco1023/poi-tl-ext/files/6694488/word.txt)
> > 
> > 
> > 行内元素使用margin或者padding在word中没有对应的样式来控制。你可以仔细看下text() 方法的实现，其实是对 getWholeText() 进行了一次字符拼接，把首尾的多个空白字符限制为最多一个，这里可以按需自定义。
> 
> 好的，这几天也看了好多，奈何水平不够，有些地方看不懂，你是对着apache poi的那个api文档（[http://poi.apache.org/apidocs/4.1/）硬撸的吗，想请教下还有什么这方面的文档](http://poi.apache.org/apidocs/4.1/%EF%BC%89%E7%A1%AC%E6%92%B8%E7%9A%84%E5%90%97%EF%BC%8C%E6%83%B3%E8%AF%B7%E6%95%99%E4%B8%8B%E8%BF%98%E6%9C%89%E4%BB%80%E4%B9%88%E8%BF%99%E6%96%B9%E9%9D%A2%E7%9A%84%E6%96%87%E6%A1%A3)

其实主要看的是[OpenXML](http://officeopenxml.com/index.php)的文档，首先要了解docx是个什么样的结构，有时还需要在word中写好内容用zip解压来看实际的xml内容，poi只是生成想要的xml结构的一种手段。

**Comment by cfx843010518** [comment]
> > 不知道为什么这样写也不行
> > [word.txt](https://github.com/draco1023/poi-tl-ext/files/6694488/word.txt)
> 
> 行内元素使用margin或者padding在word中没有对应的样式来控制。你可以仔细看下text() 方法的实现，其实是对 getWholeText() 进行了一次字符拼接，把首尾的多个空白字符限制为最多一个，这里可以按需自定义。

![image](https://user-images.githubusercontent.com/28293057/123088218-0de11f00-d458-11eb-9500-43aa3ffc5cce.png)
那这么说这些margin属性是暂时没有用到吗？ 我没看到代码有哪里进行使用到。

**Comment by draco1023** [comment]
HTML也支持在占位符所在位置渲染了，另外调整了空白字符的渲染，支持white-space样式。
