### ISSUE TITLE
富文本的图片黑了

### ISSUE THREAD

**Issue by gaoxinzhong1992** [draco1023/poi-tl-ext#100]
你好，试了2个大小不一的图片，生成word后，小一点的图片可以正常显示，大一点的图片是黑的，这是什么原因？

**Comment by gaoxinzhong1992** [comment]
> 建议先学习下如何正确的提问

模版内容：
<img width="432" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/19668967/b1843810-c56a-48b6-8910-2f3ae90589ae">

代码：
`        ZipSecureFile.setMinInflateRatio(0);
        HtmlRenderPolicy htmlRenderPolicy = new HtmlRenderPolicy();
        Configure configure = Configure.builder()
                .bind("content", htmlRenderPolicy)
                .build();
        DataM dataM = new DataM();
        // dataM.setContent("<p>asdf<img src=\"http://chaxin.360unicom.cn/files/chunkFile/7a32ded8545b24735578a3b49c57e570/biology-and-biochemistry_3.jpeg\" /></p>");
        dataM.setContent("<p>asdf<img src=\"http://chaxin.360unicom.cn/files/chunkFile/8490bb633ee0af88d92c7435341af73d/小机器人.png\" /></p>");
         XWPFTemplate.compile("/Users/rzht/Desktop/input.docx", configure).render(dataM).writeToFile("output.docx");`

biology-and-biochemistry_3.jpeg这个图片生成的效果如下：
<img width="550" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/19668967/f67f9ea1-ef29-4cef-b31f-9803eb85397b">
小机器人.png这个图片生成的效果如下：
<img width="626" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/19668967/7fe17f08-2cbd-443d-8a13-166b4b4319a4">

**Comment by gaoxinzhong1992** [comment]
刚刚又试了下图片的类型，jpg和png都可以，jpeg不行。

**Comment by draco1023** [comment]
这张jpeg图片本身就有问题，虽然是jpeg作为后缀，但是实际是png格式的

**Comment by gaoxinzhong1992** [comment]
好的，明白了。
