### ISSUE TITLE
poi-tl1.5适配哪个版本啊

### ISSUE THREAD

**Issue by DavidLee1688** [draco1023/poi-tl-ext#101]
poi-tl1.5适配哪个版本啊

**Comment by draco1023** [comment]
README里写明了啊

**Comment by DavidLee1688** [comment]
基于poi-tl1.5，poi 3.x，目前的poi-tl-ext的版本是不是都适配不了啊

**Comment by draco1023** [comment]
我不清楚poi-tl 1.5， poi 3.x与poi 4.x版本有哪些差异，你可以尝试一下看有没有问题，或者考虑以下升级
