### ISSUE TITLE
区块标签padding和换行的问题

### ISSUE THREAD

**Issue by liudechao1** [draco1023/poi-tl-ext#104]
作者你好，在使用的过程遇到两个问题，还望解答，感谢！
1、p和h1等区块标签，行内样式使用padding时不起作用，span标签可以起作用，例如：
![image](https://github.com/draco1023/poi-tl-ext/assets/24578709/3e189961-df2e-43ab-9c0b-7deea6370cd2)

生成word后，缩进效果没有产生(换成span标签可以生效)：
![image](https://github.com/draco1023/poi-tl-ext/assets/24578709/0cdc7e54-e62b-429a-bbe2-86414d518052)

2、两个p标签之前使用br，生成的word换行会有两行，例如：
![image](https://github.com/draco1023/poi-tl-ext/assets/24578709/a5d13287-0738-4165-9def-d35e2098369c)
word效果如下（如果不是区块元素换行没问题）：
![image](https://github.com/draco1023/poi-tl-ext/assets/24578709/354c3ab3-c3b9-40a4-81ce-75317d7947d0)

想请问一下这两个问题可有解决方案

**Comment by draco1023** [comment]
第一个问题，对于段落而言并没有padding这一说，只有表格的单元格有，你可以试试margin
第二个问题，等有时间了再看看

**Comment by liudechao1** [comment]
> 第一个问题，对于段落而言并没有padding这一说，只有表格的单元格有，你可以试试margin 第二个问题，等有时间了再看看

第一个把padding换成margin有效，感谢，但是我看浏览器p标签是支持padding的，后面再看看这块。
