### ISSUE TITLE
如果模板填充时，一个tag里面同时含有html和latex怎么处理

### ISSUE THREAD

**Issue by leimingshuan** [draco1023/poi-tl-ext#108]
**Describe the bug**

**HTML content:**
<p>Some html content to reproduce the issue</p>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.3.12]

**poi-tl version:**
[e.g. 1.9.1]

**Additional context**

**Comment by draco1023** [comment]
html里加了个自定义的`latex`标签支持

**Comment by leimingshuan** [comment]
> html里加了个自定义的`latex`标签支持

具体在哪里，没看到具体的实现

**Comment by dpc0828** [comment]
> > html里加了个自定义的`latex`标签支持
> 
> 具体在哪里，没看到具体的实现

<latex>公式</latex>

**Comment by dpc0828** [comment]
> > html里加了个自定义的`latex`标签支持
> 
> 具体在哪里，没看到具体的实现

        String mathString = "<latex>\\(\\left ( {x+a} \\right )^{2}=\\sum ^{n}_{k=0} {\\left ( {^{中文测试}_{￥}} \\right ){x}^{k}{a}^{n-k}}\\)</latex>";

**Comment by leimingshuan** [comment]
> > > html里加了个自定义的`latex`标签支持
> > 
> > 
> > 具体在哪里，没看到具体的实现
> 
> ```
>     String mathString = "<latex>\\(\\left ( {x+a} \\right )^{2}=\\sum ^{n}_{k=0} {\\left ( {^{中文测试}_{￥}} \\right ){x}^{k}{a}^{n-k}}\\)</latex>";
> ```
前几天看到了具体实现，谢谢
