### ISSUE TITLE
new TOCRenderPolicy()未生效

### ISSUE THREAD

**Issue by JIQ914915** [draco1023/poi-tl-ext#112]
**Describe the bug**
已经配置了TOCRenderPolicy，但是用WPS打开生成的文档，并没有弹出更新域的提示，且目录为空

**Screenshots**
这个是我的测试代码
![image](https://github.com/draco1023/poi-tl-ext/assets/27619925/0230a215-dacb-4372-bdb6-aa9071e28408)
这个是我的word模板
![image](https://github.com/draco1023/poi-tl-ext/assets/27619925/e52540fa-ede7-4b3e-827c-c447c01eb3e4)

**poi-tl version:**
1.12.2

**Additional context**

**Comment by draco1023** [comment]
你应该到 https://github.com/Sayi/poi-tl 去提issue
