### ISSUE TITLE
渲染word的时候，有一个表格和换行<br>在一起时，渲染不上。

### ISSUE THREAD

**Issue by Wangqi0326** [draco1023/poi-tl-ext#114]
**Describe the bug**
Caused by: org.apache.xmlbeans.impl.values.XmlValueDisconnectedException: null
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
	at org.apache.xmlbeans.impl.values.XmlObjectBase.newCursor(XmlObjectBase.java:286)
	at org.ddr.poi.html.HtmlRenderPolicy.hasSibling(HtmlRenderPolicy.java:181)
	at org.ddr.poi.html.HtmlRenderPolicy.afterRender(HtmlRenderPolicy.java:165)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:67)
	... 125 common frames omitted
11:26:12.508 [http-nio-9099-exec-2] WARN  o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - [logException,208] - Resolved [com.deepoove.poi.exception.RenderException: Unable to render template {{content}}]

**HTML content:**
<div style="text-align: center;"><h1><span style="font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(255, 0, 0); font-weight: 600; font-size: 26px;">授权协议</span></h1></div><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">本企业（企业名称：</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">上海和科设备制造有限公司</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">统一社会信用代码：</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">9131000078721575X</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">） 同意并授权 </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">中国建设银行</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">（称为 “被授权方”）可在有效期内查询本企业相关数据，具体如下：</span><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;"><br></span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">1.</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 9px;">&nbsp; </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">被授权方在本次授权下，所查询的信用信息用途包括（1）贷前评估审查；（2）贷后风险监测分析；（3）信用服务机构提供市场化信用评价/评级服务；（4）根据法律法规、监管部门要求或其他经本企业另行明确同意的用途。</span><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;"><br></span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">2.</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 9px;">&nbsp; </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">本企业知晓并同意，</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">本企业有权单方撤销对被授权方的信息查询授权。</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">但如果本企业与被授权方的业务关系尚未终止，在具体产品或服务项下存在应偿付款项（例如借款本金和利息等）或与被授权方尚有争议的情况下，无法单方撤销本授权，须经被授权方许可同意方可撤销。</span><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;"><br></span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">3.</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 9px;">&nbsp; </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">本【授权文件】自本企业确认已阅读并同意【授权文件】，有效期为2024-07-08至2024-08-08止</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">。</span><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;"><br></span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">4.</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 9px;">&nbsp; </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">本企业知悉并同意</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">，在查询和使用本企业信息时，上述被授权方将采取必要措施保障信息安全，防止信息非法泄露或不当使用。</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">上述被授权方超出上述授权查询、使用本企业信息的一切后果和法律责任由被授权方承担。</span><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;"><br></span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">5.</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 9px;">&nbsp; </span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">本企业知悉并理解</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-size: 18px;">，上述被授权方有权在本次授权用途下，合法合规使用在本次授权范围内通过平台方查询的信息，并作出判断、决定等行为。</span><span style="font-family: &quot;Microsoft YaHei&quot;; color: rgb(0, 0, 0); font-weight: 600; font-size: 18px;">平台方、政府部门以及其他信息来源主体不对被授权方作出的判断、决定等行为及其后果承担任何法律责任。</span><table cellspacing="0" cellpadding="0" border="0" style="border-top: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); width: 554px;"><colgroup><col width="277"><col width="277"></colgroup><tbody><tr style="height: 42px;"><td colspan="1" rowspan="1" style="border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;"><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;">789</span></td><td colspan="1" rowspan="1" style="border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;"><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;">789</span></td></tr><tr style="height: 42px;"><td colspan="1" rowspan="1" style="border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;"><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;">123</span></td><td colspan="1" rowspan="1" style="border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;"><span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;">123</span></td></tr></tbody></table>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.3.12]
0.4.15

**poi-tl version:**
[e.g. 1.9.1]
1.10.5

**Additional context**

**Comment by draco1023** [comment]
see #110
