### ISSUE TITLE
富文本中插入的图片被放大

### ISSUE THREAD

**Issue by guopanwang** [draco1023/poi-tl-ext#116]
**Describe the bug**
富文本中的插入的图片被放大，点击重设大小后会恢复正常

**HTML content:**
`<p><img src="http://图片地址" style=""/></p>`
即使style中设置了长宽也会比实际的大

**Expected behavior**
希望不被放大

**Screenshots**
![1721616596859](https://github.com/user-attachments/assets/e1b63f74-6cb6-45c6-86d2-db41f9abf040)

**poi-tl-ext version:**
[e.g. 0.4.16-poi5]

**poi-tl version:**
[e.g. 1.12.2]

**Additional context**
无

**Comment by draco1023** [comment]
请提供具体的html，测试时没发现有这个问题

**Comment by guopanwang** [comment]
> 请提供具体的html，测试时没发现有这个问题
<p><img src="图片地址" style=""/></p>就这样很简单，这是测试用的图片
![图片2](https://github.com/user-attachments/assets/624ad5dd-85ed-41c5-b152-92d46ff1e15b)
，

**Comment by draco1023** [comment]
如果提供一下都这么难，那也很简单，帮不了你

**Comment by guopanwang** [comment]
![image](https://github.com/user-attachments/assets/117266cc-f267-4c6f-b22a-3b8ee481acb6)
这不提供了吗？刚开始提问题的时候也给了的，就是这样呀，src是内网obs地址很长就删掉了

**Comment by draco1023** [comment]
样式是空？然后对象存储的地址是否带有图片调整的参数？

**Comment by guopanwang** [comment]
样式是空的，抱歉这点忘记特殊说明了，地址里没有带图片调整的参数，目前我这边富文本插入图片后不改变大小是没有长宽参数的，希望导入的图片大小和在word中直接导入的大小一致，我上面提供了测试的图片

**Comment by draco1023** [comment]
测试了一下，是这张图片本身以及对象存储共同引发的问题，我下载到本地用图片浏览器查看是png格式的，尺寸为276*190，因为后缀是jpg，上传到某图床后被识别为jpeg格式，这样下载下来格式为jpeg，尺寸变成了248*171，但是我把图片上传到阿里云OSS，下载下来格式还是png，尺寸是276*190的
