### ISSUE TITLE
mark标签背景色不显示

### ISSUE THREAD

**Issue by Zjimily** [draco1023/poi-tl-ext#118]
**Describe the bug**
mark标签下背景色不显示,p标签下显示

**HTML content:**
<mark style="background-color: #ff0200">test</mark>

**Expected behavior**
 HtmlRenderPolicy htmlRenderPolicy = new HtmlRenderPolicy();
        Configure configure = Configure.builder()
                .bind("teachContent", htmlRenderPolicy)
//                .bind("plainContent", htmlRenderPolicy)
                .build();
        Map<String, Object> data = new HashMap<>(2);
        data.put("teachContent", "<mark style=\"background-color: lightblue\">test</mark>");
//        data.put("teachContent", FileReader.readFile("/1.html"));
//        data.put("plainContent", FileReader.readFile("/2.html"));

        try (InputStream inputStream = HtmlRenderPolicyTest.class.getResourceAsStream("/notes.docx")) {
            XWPFTemplate.compile(inputStream, configure).render(data).writeToFile("notes_out.docx");
        }

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.4.16-poi5]

**poi-tl version:**
[e.g. 1.12.2]

**Additional context**

**Comment by draco1023** [comment]
请使用0.4.17版本
