### ISSUE TITLE
富文本无序列表+行间距，图片标题，可选框不显示问题

### ISSUE THREAD

**Issue by Zjimily** [draco1023/poi-tl-ext#119]
**Describe the bug**
富文本无序列表+行间距，图片标题，可选不显示问题

**HTML content:**
无序列表+行间距：
<ul><li><p style="text-align: justify; line-height: 4"><span style="font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)">此次活动吸引了大量的社区居民前来</span></p></li><li><p style="text-align: justify; line-height: 4"><span style="font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)">军山院区医疗团队累计接诊咨询230余人次，血压测量150人次，血糖测量103人次，超声检查35人次，药物咨询50人次</span></p></li><li><p style="text-align: justify; line-height: 4"><span style="font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)">充分体现了纱帽地区的居民对健康的关注与需求。</span></p></li></ul>
图片标题：
<span style="display: flex; flex-direction: column; align-items: center;"><img src="https://img2.baidu.com/it/u=3674949754,3380308497&fm=253&fmt=auto&app=120&f=JPEG?w=500&h=333" alt="义诊现场" width="740" height="493" data-display="align-right"><input value="义诊现场" type="text" readonly="true" style="display: inline-block;text-align:center;border:unset;outline:none;"></span>

可选框不显示：							
<label><input type="checkbox"><span></span></label>		

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[0.4.17-poi5]

**poi-tl version:**
[1.12.2]

**Additional context**

**Comment by Zjimily** [comment]
<span style=\"display: flex; flex-direction: column; align-items: center;\"><img src=\"https://img2.baidu.com/it/u=3674949754,3380308497&fm=253&fmt=auto&app=120&f=JPEG?w=500&h=333\" alt=\"义诊现场\" width=\"740\" height=\"493\" data-display=\"align-right\"><input value=\"义诊现场\" type=\"text\" readonly=\"true\" style=\"display: inline-block;text-align:center;border:unset;outline:none;\"></span>
			
			<label><input type=\"checkbox\"><span></span></label>
			
			<ul><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">此次活动吸引了大量的社区居民前来</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">军山院区医疗团队累计接诊咨询230余人次，血压测量150人次，血糖测量103人次，超声检查35人次，药物咨询50人次</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">充分体现了纱帽地区的居民对健康的关注与需求。</span></p></li></ul>

**Comment by draco1023** [comment]
word中不支持input

**Comment by Zjimily** [comment]
感谢回复，另外2个不显示问题，麻烦帮忙也看下：
**无序列表+行间距：**
`<ul><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">此次活动吸引了大量的社区居民前来</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">军山院区医疗团队累计接诊咨询230余人次，血压测量150人次，血糖测量103人次，超声检查35人次，药物咨询50人次</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">充分体现了纱帽地区的居民对健康的关注与需求。</span></p></li></ul>`
**可选框不显示：**
`<label><input type=\"checkbox\"><span></span></label>`

**Comment by draco1023** [comment]
无序列表的可以显示，可选框还是input，不支持

**Comment by Zjimily** [comment]
我测试发现的效果如下：
**设置行间距**
`<p style="text-align: justify; line-height: 4"><span style="font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)">此次活动吸引了大量的社区居民前来，军山院区医疗团队累计接诊咨询230余人次，血压测量150人次，血糖测量103人次，超声检查35人次，药物咨询50人次 ，充分体现了纱帽地区的居民对健康的关注与需求。</span></p>`
**这个导出后在word中看行距多倍行距是4**
**无序列表+行间距：**
`<ul><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">此次活动吸引了大量的社区居民前来</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">军山院区医疗团队累计接诊咨询230余人次，血压测量150人次，血糖测量103人次，超声检查35人次，药物咨询50人次</span></p></li><li><p style=\"text-align: justify; line-height: 4\"><span style=\"font-family: 微软雅黑; font-size: 20px; color: rgb(51, 51, 51)\">充分体现了纱帽地区的居民对健康的关注与需求。</span></p></li></ul>`
**这个导出后在word中看行距多倍行距是1**
这2种样式在word中效果如下图：
![Uploading 5EDC8288-EB39-4a63-86A8-E9C0D6C11CA5.png…]()

**Comment by Zjimily** [comment]
![5EDC8288-EB39-4a63-86A8-E9C0D6C11CA5](https://github.com/user-attachments/assets/0c4db028-1c3d-4cd2-83c0-b11a858699d9)

**Comment by draco1023** [comment]
请使用`0.4.18-poi5`版本
