### ISSUE TITLE
Unable to set indent for bullets

### ISSUE THREAD

**Issue by darkalto2009** [draco1023/poi-tl-ext#120]
**Describe the bug**
@draco1023
I want to use HTMLRenderPolicy.java to set paragraphs. The paragraph can have 'ul' and 'ol' tags. I am trying to set the indent of the created bullets, but it getting set as 0. The issue is with the NumberingContext.java where the below code is written:

                        CTInd ind = cTLvl.addNewPPr().addNewInd();
                        ind.setLeft(BigInteger.valueOf(indent * i));

Here, when i = 0, then indent is set to 0, even when I try to set a value. Can we change this to below?

                        CTInd ind = cTLvl.addNewPPr().addNewInd();
                        ind.setLeft(BigInteger.valueOf(indent * (i+1)));
                        ind.setHanging(BigInteger.valueOf(hanging * (i+1)));

Also, can we add another configuration for ind.setHanging(...)? We can add a variable in HtmlRenderConfig.java just like custom numbering indent. 

**HTML content:**
<ul><li>List 1</li><li>List 2</li><li>List 3</li></ul>

**Expected behavior**
When I am setting the custom numbering indent in HtmlRenderConfig.java, I expect the indent to be applied properly. Also, indent hanging property should be available to format the bullet.

**poi-tl-ext version:**
0.4.15-poi5

**poi-tl version:**
1.12.2

**Comment by draco1023** [comment]
`Indent` is used to indicate the indentation between parent and child lists. For the first level offset, it's recommended to use `margin` or `padding` on the `ul` or `ol` tag. As for whether to add `hanging`, I will consider it.

**Comment by darkalto2009** [comment]
@draco1023, please let me know, by when can I expect the changes to be released?

**Comment by draco1023** [comment]
Try `0.4.18-poi5`

**Comment by darkalto2009** [comment]
@draco1023 Thank you for the quick turn around. 
The variable left added to ListStyle helps in adding space before the bullet. But with indent we can control the space between the bullet and paragraph.

![image](https://github.com/user-attachments/assets/1772b1a3-b18a-4d68-984f-b66d00252e33)

**In the screenshot**
_Bullet position_: is equivalent to the 'left' variable in ListStyle.java
_Text indent_: is the indent we need. That is the space between the bullet and text
_Follow number with_: is the minimum space between the bullet and text
