### ISSUE TITLE
html文本标签填充后是空白的

### ISSUE THREAD

**Issue by acodebird** [draco1023/poi-tl-ext#15]
### 依赖：
![image](https://user-images.githubusercontent.com/43145321/135200041-c9ac0682-3a24-462d-b738-e10cdcfa3713.png)

### 代码：
![image](https://user-images.githubusercontent.com/43145321/135199985-5cbcaa2c-490b-434e-aaee-3fadda609c31.png)

### 模板：
![image](https://user-images.githubusercontent.com/43145321/135199823-f011f41c-aade-422b-89ef-afb80102b40b.png)

### 生成结果：
![image](https://user-images.githubusercontent.com/43145321/135199792-5eef944c-5a2e-4c8b-91e3-67bc9cab6c20.png)

**Comment by draco1023** [comment]
请提供下模板文件

**Comment by draco1023** [comment]
长时间未回复
