### ISSUE TITLE
针对同一个模板参数，如何同时使用HtmlRenderPolicy与LaTeXRenderPolicy？

### ISSUE THREAD

**Issue by slivercb** [draco1023/poi-tl-ext#20]
比如有一个题目数据：<p style="background-color:white;color:black;">阅读下面的材料:解方程组\( \{ {^{\frac {3} {x}+\frac {2} {y}=7,}_{\frac {2} {x}-\frac {1} {y}=14}} \)时,若设\( \frac {1} {x}=m \),\( \frac { 1 } { y } = n \)则原m,n方程组可变形为关于m,n的方程组 \( \{ {^{3m+2n=7,}_{2m-n=14.}} \),解这个方程组,得到它的解为\( \{ {}{^{m=5,}_{n=-4.}} \)</p><p style="background-color:white;color:black;">这由\( \frac { 1 } { x } = 5 \),\( \frac { 1 } { y } = -4 \),求得原方程组的解为\( \{ {^{x=\frac {1} {5},}_{y=-\frac {1} {4}.}} \)</p><p style="background-color: white; color: black;">利用上该方法解方程组:\( \{ {^{\frac {5} {x}+\frac {2} {y}=11,}_{\frac {3} {x}-\frac {2} {y}=13.}} \) </p>

这种同时有html标签，又有laTex标签的，需要放到一个模板参数中的如何处理？

**Comment by draco1023** [comment]
LaTeX并不属于HTML兼容的标记语言，最大的问题在于无法在HTML中判断LaTeX的标记边界，故而无法支持同时进行二者的处理

**Comment by draco1023** [comment]
poi-tl本身也不支持同时使用多种渲染策略

**Comment by draco1023** [comment]
添加了自定义标签`<latex>`以支持在HTML中混入LaTeX，见 8145a812d1de2f7de65237c86b38fd820352d33f
