### ISSUE TITLE
请问依赖的poi-tl版本后续会升级成最新的版本吗？

### ISSUE THREAD

**Issue by RuiCR** [draco1023/poi-tl-ext#25]

**Comment by draco1023** [comment]
`poi-5` 分支已经将 `poi-tl` 升级到1.11.0版本，如果想升级，请使用 `0.3.11-beta` 版本

**Comment by JAVAXUAN** [comment]
你好，我转换html为docx总是会开头自动换行两行，不论换哪种html都是，这是为什么呀

**Comment by draco1023** [comment]
`poi-tl` 1.11.0 以下版本请使用 `x.x.xx` 版本
`poi-tl` 1.11.0 及以上版本请使用 `x.x.xx-beta` 版本
