### ISSUE TITLE
table如果最后一列带有rowspan不会生成合并单元格

### ISSUE THREAD

**Issue by hujun82589167** [draco1023/poi-tl-ext#27]
<table border='1' style='width: 100%;'>
    <tbody>
    <tr style='border: solid #CCCCCC 1.0pt; background: #F2F2F2;'>
        <td style='width:30%;text-align:center'><b>所属权限组</b></td>
        <td style='width:40%;text-align:center'><b>敏感权限（声明权限）</b></td>
        <td style='width:30%;text-align:center'><b>测试期间是否存在实际调用</b></td>
    </tr>
    <tr>
        <td rowspan=2 style='text-align:center'>STORAGE(存储权限)</td>
        <td style='text-align:center'>android.permission.ACCESS_MEDIA_LOCATION(读取照片位置信息)</td>
        <td style='word-break: break-all;color:red;text-align:center'>否</td>
    </tr>
    <tr>
        <td style='text-align:center'>android.permission.WRITE_EXTERNAL_STORAGE(写入外部存储)</td>
        <td style='word-break: break-all;text-align:center'>是</td>
    </tr>
    <tr>
        <td rowspan=2 style='text-align:center'>PHONE(电话权限)</td>
        <td style='text-align:center'>android.permission.READ_PHONE_NUMBERS(读取本机电话号码)</td>
        <td style='word-break: break-all;color:red;text-align:center'>否</td>
    </tr>
    <tr>
        <td style='text-align:center'>android.permission.READ_PHONE_STATE(读取电话状态)</td>
        <td style='word-break: break-all;text-align:center'>是</td>
    </tr>
    <tr>
        <td rowspan=1 style='text-align:center'>LOCATION(定位权限)</td>
        <td style='text-align:center'>android.permission.ACCESS_FINE_LOCATION(访问精准定位)</td>
        <td style='word-break: break-all;color:red;text-align:center'>否</td>
    </tr>
    <tr>
        <td rowspan=1 style='text-align:center'>MICROPHONE(麦克风权限)</td>
        <td style='text-align:center'>android.permission.RECORD_AUDIO(录音)</td>
        <td rowspan=2 style='word-break: break-all;text-align:center'>是</td>
    </tr>
    <tr>
        <td rowspan=1 style='text-align:center'>CAMERA(相机权限)</td>
        <td style='text-align:center'>android.permission.CAMERA(拍摄)</td>
    </tr>
    </tbody>
</table>

**Comment by draco1023** [comment]
请提供html内容
