### ISSUE TITLE
和poi-tl V1.11.0  版本不兼容

### ISSUE THREAD

**Issue by pmtea** [draco1023/poi-tl-ext#28]
和POI-TL最新版不兼容，应该是因为用的POI需要是5.1.0 版本
我折腾了半天，但是水平有限，梳理不清楚哪个包要升级
ooxx-ml
poi-ooxx
什么的，还有maven的依赖搞的我头的晕了，
最后还是使用了POI-TL1.9.1版本了，反正也能用 😄

**Comment by ditaps** [comment]
同需要poi 5.1.0 
改依赖，然后又改了一部分源码，还是失败了

**Comment by draco1023** [comment]
`poi-5` 分支已经将 `poi-tl` 升级到1.11.0版本，如果想升级，请使用 `0.3.11-beta` 版本

**Comment by pmtea** [comment]
> `poi-5` 分支已经将 `poi-tl` 升级到1.11.0版本，如果想升级，请使用 `0.3.11-beta` 版本

非常感谢
