### ISSUE TITLE
怎样把前端传入的富文本字符串导出到word

### ISSUE THREAD

**Issue by KevinPan1992** [draco1023/poi-tl-ext#31]
前端使用tinymce富文本编辑器，提交到后台的是一个字符串，如何直接根据这个字符串导出内容；（字符串格式：<p style=\"text-align: left;\"><strong><span style=\"font-size: 18pt;\">）

**Comment by draco1023** [comment]
这是你的代码逻辑要解决的问题，而不是本类库要解决的问题，请不要提这种无关的问题
