### ISSUE TITLE
渲染样式，目标【段落】无法设置【行间距】

### ISSUE THREAD

**Issue by iguojing** [draco1023/poi-tl-ext#32]
渲染出来的段落，行间距为 1.0

HtmlRenderConfig 可以开放【设置行距】的参数吗？

(另：谢谢作者， 这真的是一个非常方便的 ext！)

**Comment by draco1023** [comment]
行距的设置是留了一个TODO的，只是对于段落生效，暂时没想到有在 HtmlRenderConfig 中开放设置的必要。按照预期是通过设置 CSS 样式中的 `line-height`（行间距）、`margin-top`（段前）、`margin-bottom`（段后） 来达到为段落设置行距的目的。

**Comment by draco1023** [comment]
@iguojing 已支持行距设置，`poi`版本4.x 请使用`0.3.12`版本，5.x 请使用`0.3.12-beta`版本

**Comment by ejiyuan** [comment]
大神们？这个行距设置入口在哪里？谢谢~

**Comment by draco1023** [comment]
> 大神们？这个行距设置入口在哪里？谢谢~

设置`line-height`样式
