### ISSUE TITLE
渲染失败

### ISSUE THREAD

**Issue by qyw10456** [draco1023/poi-tl-ext#35]
大佬您好
`
HtmlRenderPolicy htmlRenderPolicy = new HtmlRenderPolicy();
Configure configure = Configure.builder().bind("context", htmlRenderPolicy).build();
Map<String, Object> hashMap = new HashMap<>();
hashMap.put("context", safeTrain.getTrainContext());
 XWPFTemplate template  = XWPFTemplate.compile(FileUtils.getInputStream(URL),configure).render(hashMap);
`
![image](https://user-images.githubusercontent.com/86226719/154236747-0b7d7cc7-99de-4f11-9c21-e6ba0ed8ed75.png)
发现并没有渲染标签，这是我用的版本
![image](https://user-images.githubusercontent.com/86226719/154237040-d639d546-c04c-4c78-bb0b-bcbfa1fca9b6.png)
不知道哪里有问题，求大佬指教

**Comment by draco1023** [comment]
请先检查html内容是否正确，poi-tl的版本用1.10.3试试

**Comment by qyw10456** [comment]
hashMap.put("context","<p>Hello <b>world</b>!</p>");
![image](https://user-images.githubusercontent.com/86226719/154601765-15b70d70-fa68-4d58-8949-1c158d71b6bc.png)
换成1.10.3还是不行

**Comment by qyw10456** [comment]
这里put的值里有标签，被自动装换了，我直接复制的你示例里的值
