### ISSUE TITLE
生成的公式是斜体的，如何取消斜体？

### ISSUE THREAD

**Issue by liuxianfa520** [draco1023/poi-tl-ext#41]
**Describe the bug**
生成的公式是斜体的：
![image](https://user-images.githubusercontent.com/22516200/164225057-421cfec6-937a-42f2-a24e-72695ca1c750.png)

需求方想要让生成的公式不是斜体的。
请问应该如何设置呢？

代码：

    public static void main(String[] args) throws IOException {
        HashMap<Object, Object> param = new HashMap<>();
        param.put("symbol", "$$ A_{f} $$");

        Configure config = Configure.builder()
                                    .bind("symbol", new LaTeXRenderPolicy())
                                    .build();
        XWPFTemplate template = XWPFTemplate.compile("d://text.docx", config).render(param);
        template.writeAndClose(new FileOutputStream("d://" + System.currentTimeMillis() + ".docx"));
    }

模板：
![image](https://user-images.githubusercontent.com/22516200/164225230-e4924fdc-2b9e-45ce-b8ea-5bad34ca3e8f.png)

**HTML content:**

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
0.3.14

**poi-tl version:**
1.10.0

**Additional context**

**Comment by draco1023** [comment]
这些LaTex字符正常呈现出来就是斜体的

**Comment by liuxianfa520** [comment]
> 这些LaTex字符正常呈现出来就是斜体的

恩恩，是的。latex正常情况，或者说默认情况，解析出来是斜体的。

但是我们想要设置成正体。所以想学习一下，应该如何设置。


我在网上找搜索：LaTeX中公式中的字体变正体   
找到两篇文章，试了一下，没有起作用：
https://blog.csdn.net/wanjiac/article/details/115729149
https://www.cnblogs.com/yymn/p/15179433.html


`
一定将 \rm 输在 $$ 里面~！！！
{$ \rm  kg/m^{3} $}
`

**Comment by draco1023** [comment]
$$ \textrm{A}_{\textrm{f}} $$
这样可行  不过用起来比较麻烦  不能对整个公式使用一个 \textrm 标签包起来  得对每个字符串单独处理

**Comment by draco1023** [comment]
从转换的日志来看 \rm 其实是有效的，产生的 MathML 如下
```xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
    <mstyle mathvariant="normal">
        <msub>
            <mi>A</mi>
            <mi>f</mi>
        </msub>
    </mstyle>
</math>
```
但是从 MathML 转 OMath 的时候 mstyle 中的属性被忽略了，原因是 MML2OMML.XSL 中所有读取样式属性的地方都没有考虑从 mstyle 继承样式，所以看起来没有效果

**Comment by liuxianfa520** [comment]
好的，非常感谢！！！我去试试去

**Comment by liuxianfa520** [comment]
完美。亲测可用。
感谢！感谢！感谢！
![image](https://user-images.githubusercontent.com/22516200/164616957-85d4998c-8c71-4e94-bef7-ec548041bc4c.png)

**Comment by liuxianfa520** [comment]
您好，
我是使用您的第二种方案，也就是修改 MML2OMML.XSL 配置文件的方式。
我又发现一个小小的问题，看看能不能解决：


对于  
`$$ \rm G_{s} $$`
这种，下标只有一个字母的，可以正常展示，都是正体：
![image](https://user-images.githubusercontent.com/22516200/164661455-dbb55edf-055d-401f-9e4c-1bc43af34f6a.png)


但是，如果下标有多个字母，比如：
`$$ \rm D_{out} $$`
则下标  out 中 ，第一个字母 o 是正体，从第二个字母开始，都是斜体：
![image](https://user-images.githubusercontent.com/22516200/164664054-c7ee5751-fb6d-4ae8-92bf-f0ad47e36522.png)

![image](https://user-images.githubusercontent.com/22516200/164665267-c154ee30-ac50-44b7-9795-cec82706220f.png)




有时间的话，还请您帮忙看一下，有没有什么解决办法。

**Comment by draco1023** [comment]
还是推荐使用第一种，用 $$ \textrm{D}_{\textrm{out}} $$ 就可以，第二种暂时没时间看是什么问题

**Comment by liuxianfa520** [comment]
> 还是推荐使用第一种，用 $$ \textrm{D}_{\textrm{out}} $$ 就可以，第二种暂时没时间看是什么问题

好的，还是用这种把。写个转换的方法就行了。
谢谢啦~~~
