### ISSUE TITLE
请问在 <ul> 中，如何自定列表项的编号？如何调整编号与内容之间的间距？

### ISSUE THREAD

**Issue by zhtaihao** [draco1023/poi-tl-ext#42]
- [`org.ddr.poi.html.util.ListStyleType`](https://github.com/draco1023/poi-tl-ext/blob/main/src/main/java/org/ddr/poi/html/util/ListStyleType.java#L17) 中默认的 level 1 符号是 ⚫ (Wingdings \uF06C)。这个符号能在使用时改变吗？

- [`org.ddr.poi.html.util.NumberingContext`](https://github.com/draco1023/poi-tl-ext/blob/main/src/main/java/org/ddr/poi/html/util/NumberingContext.java#L49) 中的 `int INDENT = 360;` 能在使用时改变吗？

**Comment by zhtaihao** [comment]
目前给出的列表这个样：
![image](https://user-images.githubusercontent.com/46465678/170614044-e37377a3-425f-4504-8dbc-7a5675861941.png)

现在在找办法自己定一个符号代替 `⚫`，而且减少符号与句子之间的空间。

**Comment by zhtaihao** [comment]
现在通过以下方式代替了符号，有比这个好的办法吗？
```java
class MyListItemRenderer extends ListItemRenderer {
  @Override
  public boolean renderStart(final Element element, final HtmlRenderContext context) {
    context.getNumberingContext().endLevel();
    context.getNumberingContext().startLevel(ListStyleType.Unordered.SQUARE);
    return super.renderStart(element, context);
  }
}
```
```java
    var htmlConfig = new HtmlRenderConfig();
    htmlConfig.setCustomRenderers(List.of(new MyListItemRenderer()));
    var htmlRenderPolicy = new HtmlRenderPolicy(htmlConfig);
```
____
还没有找到办法改变空间的大小，非常感谢如果能帮助。

**Comment by draco1023** [comment]
https://github.com/draco1023/poi-tl-ext/blob/c53f3e02f39ad92890dca9809bedc32e94af046e/src/main/java/org/ddr/poi/html/util/NumberingContext.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L49

缩进是使用`INDENT`控制的

**Comment by zhtaihao** [comment]
不好意思开了 #44  之后才看见你在这里写的回复。
觉得 INDENT 稍微有点大，要是能通过一个 Setter （见#44）随时改变的话能挺方便的。

**Comment by draco1023** [comment]
已发布`0.3.15`版本，加了个配置项`numberingIndent`.

**Comment by zhtaihao** [comment]
谢谢这么迅速地实施了这个功能。我很好奇想问一下，使用 `Integer` 而不是 `int` 有一定理由吗？`int` 不其实自动就拍除了 `null` 的可能性吗？

**Comment by draco1023** [comment]
因为默认情况下不需要修改设置，如果使用`int`就必须在设置的时候进行一次判断

**Comment by zhtaihao** [comment]
https://github.com/draco1023/poi-tl-ext/blob/f91be9e66ab90d8f91a48e4968f2ddfdec63239f/src/main/java/org/ddr/poi/html/util/NumberingContext.java#L143-L147

在这里的 `i` 始终为 0，所以无论 `indent` 之前被调到多少，它跟 0 相乘之后又是 0。
那难道之前的缩进根本不是被 `INDENT = 360` 控制的吗？

**Comment by zhtaihao** [comment]
很好用，谢谢！我把issue标题稍微改了以下，这样别人遇见同样问题方便搜到这个条子。
