### ISSUE TITLE
find a bug or error：Caused by: java.lang.NoSuchMethodError: 'java.math.BigInteger org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageSz.getW()

### ISSUE THREAD

**Issue by 13771412500** [draco1023/poi-tl-ext#47]
**Describe the bug**
Caused by: java.lang.NoSuchMethodError: 'java.math.BigInteger org.openxmlformats.schemas.wordprocessingml.x2006.main.CTPageSz.getW()'.

**HTML content:**
<p><br class="ProseMirror-trailingBreak"></p >

**poi-tl-ext version:**
[e.g. 0.3.18]

**poi-tl version:**
[e.g. 1.12.0]

**Comment by draco1023** [comment]
Please read the document first and use the compatible version with `poi-tl`.

**Comment by 13771412500** [comment]
> Please read the document first and use the compatible version with `poi-tl`.

It is recommended to upgrade to the latest version of POI TL

**Comment by draco1023** [comment]
You can use the latest version of `poi-tl` by yourself, but you must use `xxx-beta` version of this lib.
