### ISSUE TITLE
字符串拼接<p>标签，会换行

### ISSUE THREAD

**Issue by yyrely** [draco1023/poi-tl-ext#48]
普通字符拼接<p>标签的字符串，拼接前和拼接后的字符串不在同一行

java代码：
String s = “A” + “<p>信息技术</p>”；

结果：
![image](https://user-images.githubusercontent.com/36360198/182511269-a7553580-a635-496c-83c8-e9469c29456d.png)

可以做到不换行吗

**Comment by yyrely** [comment]
java代码
`String s = “A” + “<p>信息技术</p>”`

**Comment by draco1023** [comment]
p标签是块状元素  所以会换行  可以换成span标签
