### ISSUE TITLE
根据html h1/6标签 标签创建文档目录，能推荐个思路么

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#49]
根据html h1/6标签 标签创建文档目录，能推荐个思路么

**Comment by draco1023** [comment]
不明白你说的文档目录是什么样的，是在文档内容里的？还是就是作为导航里的标题？

**Comment by stringutils** [comment]
> 不明白你说的文档目录是什么样的，是在文档内容里的？还是就是作为导航里的标题？

是的，就是根据html中的h标签生成word里导航的标题

**Comment by stringutils** [comment]
需求是根据html页面生成word,我的思路是把整个html注入到一个标签中来实现

**Comment by stringutils** [comment]
需求是根据html页面生成word,我的思路是把整个html注入到一个标签中来实现

**Comment by draco1023** [comment]
@stringutils 试试0.3.19版本是不是你想要的效果

**Comment by stringutils** [comment]
> @stringutils 试试0.3.19版本是不是你想要的效果

是的，就是这个效果；不过我现在又遇到了另外一个问题，就是用TOCRenderPolicy这个目录插件生成的word,每次打开会弹框

**Comment by stringutils** [comment]
> @stringutils 试试0.3.19版本是不是你想要的效果

a.  0.3.19生成的标题样式还是文本，这样会影响自动插入目录；
b.  我现在又遇到了另外一个问题，就是用TOCRenderPolicy这个目录插件生成的word,每次打开会弹框
![565aa6ae709d2a11e8a2f8cc98ea7b2](https://user-images.githubusercontent.com/35484811/190997894-b9f70a93-2a9c-451e-9349-46096a64cde5.png)

**Comment by draco1023** [comment]
> > @stringutils 试试0.3.19版本是不是你想要的效果
> 
> a. 0.3.19生成的标题样式还是文本，这样会影响自动插入目录； b. 我现在又遇到了另外一个问题，就是用TOCRenderPolicy这个目录插件生成的word,每次打开会弹框 ![565aa6ae709d2a11e8a2f8cc98ea7b2](https://user-images.githubusercontent.com/35484811/190997894-b9f70a93-2a9c-451e-9349-46096a64cde5.png)

所以之前就问你想要的文档目录是什么样的，从你的回复来看是想要插入在文档内部的类似书的目录，0.3.19所实现的是能够在word的导航栏中看到各个标题。至于你说的弹窗的情况，是不可避免的，因为poi本身并没有对文档进行渲染，所以目录中的引用实际要对应到第几页其实是在渲染的时候才能知道的。

**Comment by stringutils** [comment]
> > > @stringutils 试试0.3.19版本是不是你想要的效果
> > 
> > 
> > a. 0.3.19生成的标题样式还是文本，这样会影响自动插入目录； b. 我现在又遇到了另外一个问题，就是用TOCRenderPolicy这个目录插件生成的word,每次打开会弹框 ![565aa6ae709d2a11e8a2f8cc98ea7b2](https://user-images.githubusercontent.com/35484811/190997894-b9f70a93-2a9c-451e-9349-46096a64cde5.png)
> 
> 所以之前就问你想要的文档目录是什么样的，从你的回复来看是想要插入在文档内部的类似书的目录，0.3.19所实现的是能够在word的导航栏中看到各个标题。至于你说的弹窗的情况，是不可避免的，因为poi本身并没有对文档进行渲染，所以目录中的引用实际要对应到第几页其实是在渲染的时候才能知道的。

是的，弹框这个应该避免不了了，除非自己用程序渲染；0.3.19中生成的标题好像还是文本格式，就是你点击到标题上，上面的格式栏中显示的还是文本，不是标题1  标题2之类的；感谢大神分享开源

**Comment by draco1023** [comment]
在html中标题的样式是由CSS决定的，同一级的标题可能有不同的样式，这个跟word里不太一样，而且如果要将格式也只为标题类型的意味着需要增加自定义样式，可能导致样式定义比较臃肿

**Comment by HYliangkai** [comment]
同问,有没有实现思路
