### ISSUE TITLE
请问有办法能去掉通过<a>标签生成的超链接文字的下划线吗，谢谢！

### ISSUE THREAD

**Issue by evolcjt** [draco1023/poi-tl-ext#50]
**Describe the bug**
通过<a>标签生成超链接，但是文字下面默认带有下划线，通过设置它的stype也没去掉

**HTML content:**
<a href='http://www.baidu.com' style='text-decoration: none;'>Hello World</a>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52807193/191884716-594b78e1-348f-4fc5-bda1-f32e1c97d88a.png)

**poi-tl-ext version:**
[e.g. 0.3.19]

**poi-tl version:**
[e.g. 1.10.4]

**Additional context**

**Comment by draco1023** [comment]
事实上是一个bug，请使用 0.3.20 版本，对a标签声明样式 `text-decoration: none` 或者 `text-decoration-line: none`
