### ISSUE TITLE
<span>标签的background-color属性不生效

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#52]
**Describe the bug**
<span>标签的background-color属性不生效
**HTML content:**
下面表格中11的标签是style="background-color:hsl(30, 75%, 60%);"
<figure class="table"><table><tbody><tr><td><span style="background-color:hsl(30, 75%, 60%);">11</span></td><td><span style="color:hsl(0, 75%, 60%);">22</span></td><td>&nbsp;</td><td>33</td><td>44</td></tr><tr><td>55</td><td>&nbsp;</td><td>66</td><td>77</td><td>8</td></tr><tr><td><u>11</u></td><td>&nbsp;</td><td>22</td><td><strong>22</strong></td><td>2</td></tr></tbody></table></figure>
**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
0.3.21

**poi-tl version:**
1.11.1

**Additional context**

**Comment by draco1023** [comment]
请按照issue模板提交

**Comment by stringutils** [comment]
> 请按照issue模板提交

我重新修改了

**Comment by stringutils** [comment]
感谢
