### ISSUE TITLE
表格中嵌套表格时，导出报错

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#53]
表格中嵌套表格时，导出报错

**Comment by draco1023** [comment]
请按照issue模板提交

**Comment by stringutils** [comment]
<img width="361" alt="78d9f7ecf897a8cb15814fc782b1c34" src="https://user-images.githubusercontent.com/35484811/195493675-6cffe49f-71d9-432e-88a6-e21a90e77c30.png">
