### ISSUE TITLE
表格中嵌套表格时，导出报错

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#54]
**Describe the bug**
表格中嵌套表格时，导出报错
**HTML content:**
<figure class="table"><table><tbody><tr><td>1</td><td>2</td><td>3</td></tr><tr><td>4</td><td>5</td><td>6</td></tr></tbody></table></figure><p><span class="cus-time" timevar="{&quot;unit&quot;:&quot;d&quot;,&quot;t&quot;:1,&quot;formate&quot;:&quot;YYYY年M月D日&quot;,&quot;value&quot;:&quot;2022年10月12日&quot;,&quot;currentDate&quot;:1665627341442,&quot;updateDate&quot;:&quot;2022-10-12 10:15&quot;}">2022年10月12日</span></p><figure class="table"><table><tbody><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td></tr><tr><td>11</td><td>21</td><td>31</td><td>41</td><td>51</td><td>61</td><td>71</td><td>81</td><td>91</td></tr><tr><td>12</td><td>22</td><td>32</td><td><figure class="table"><table><tbody><tr><td>a</td><td>b</td><td>c</td></tr><tr><td>d</td><td><figure class="table"><table><tbody><tr><td>A</td><td>B</td></tr><tr><td>C</td><td>D</td></tr></tbody></table></figure></td><td>f</td></tr><tr><td>g</td><td>h</td><td>j</td></tr></tbody></table></figure></td><td>52</td><td>62</td><td>72</td><td>82</td><td>92</td></tr><tr><td>13</td><td>23</td><td>33</td><td>43</td><td>53</td><td>63</td><td>73</td><td>83</td><td>93</td></tr><tr><td>14</td><td>24</td><td>34</td><td>44</td><td>54</td><td>64</td><td>74</td><td>84</td><td>94</td></tr></tbody></table></figure>

**Expected behavior**

**Screenshots**
<img width="361" alt="78d9f7ecf897a8cb15814fc782b1c34" src="https://user-images.githubusercontent.com/35484811/195494236-aebea17e-880c-4caf-81ee-a00d37258239.png">

**poi-tl-ext version:**
0.3.21

**poi-tl version:**
1.11.1

**Additional context**

**Comment by stringutils** [comment]
@draco1023 重新建了一个

**Comment by draco1023** [comment]
表格的渲染逻辑没有问题，但是docx里要求单元格的最后一个元素必须是段落，请使用`0.3.22`版本。

**Comment by stringutils** [comment]
> 表格的渲染逻辑没有问题，但是docx里要求单元格的最后一个元素必须是段落，请使用`0.3.22`版本。

666，现在这种嵌套的表格生成word后不报错了；但是有个小问题就是嵌套的表格不显示边框
<img width="486" alt="1665652475425" src="https://user-images.githubusercontent.com/35484811/195556432-ba031b4c-8d7a-4e83-8e97-b2b90a1b8cf6.png">
