### ISSUE TITLE
表格中嵌套表格时，嵌套的表格不显示边框

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#55]
**Describe the bug**
表格中嵌套表格时，嵌套的表格不显示边框
**HTML content:**
<figure class="table"><table><tbody><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td><td>6</td><td>7</td><td>8</td><td>9</td></tr><tr><td>11</td><td>21</td><td>31</td><td>41</td><td>51</td><td>61</td><td>71</td><td>81</td><td>91</td></tr><tr><td>12</td><td>22</td><td>32</td><td><figure class="table"><table><tbody><tr><td>a</td><td>b</td><td>c</td></tr><tr><td>d</td><td><figure class="table"><table><tbody><tr><td>A</td><td>B</td></tr><tr><td>C</td><td>D</td></tr></tbody></table></figure></td><td>f</td></tr><tr><td>g</td><td>h</td><td>j</td></tr></tbody></table></figure></td><td>52</td><td>62</td><td>72</td><td>82</td><td>92</td></tr><tr><td>13</td><td>23</td><td>33</td><td>43</td><td>53</td><td>63</td><td>73</td><td>83</td><td>93</td></tr><tr><td>14</td><td>24</td><td>34</td><td>44</td><td>54</td><td>64</td><td>74</td><td>84</td><td>94</td></tr></tbody></table></figure>
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/35484811/195560352-d90f0e6e-63e1-4a66-8f56-0dfdeb16d595.png)

**poi-tl-ext version:**
0.3.22

**poi-tl version:**
1.11.1

**Additional context**

**Comment by draco1023** [comment]
请仔细查看README，参考 #12

**Comment by stringutils** [comment]
> 请仔细查看README，参考 #12

可以了，感谢
