### ISSUE TITLE
下划线和删除线同时使用时，不显示删除线

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#56]
**Describe the bug**
下划线和删除线同时使用时，不显示删除线

**HTML content:**
<p><s><u>这里显示的内容是删除线和下划线</u></s></p>
原始代码
![1666057783317](https://user-images.githubusercontent.com/35484811/196316637-45693830-f8ff-493f-bbe3-2c88e58c8678.png)

**Expected behavior**

**Screenshots**
![1666016085921](https://user-images.githubusercontent.com/35484811/196200582-93e2a745-599e-4248-a2be-4cfe1e21a3e2.png)

![1666016367068](https://user-images.githubusercontent.com/35484811/196201681-928ee8f2-cd38-4fee-9607-88536ca2586a.png)

**poi-tl-ext version:**
 0.3.22

**poi-tl version:**
1.11.1

**Additional context**

**Comment by stringutils** [comment]
经过验证应该如果s标签和u标签同时存在时，只有内层的标签生效

**Comment by draco1023** [comment]
用 `style="text-decoration: line-through underline"` 是可以的，描述的这种组合确实没考虑

**Comment by stringutils** [comment]
> 用 `style="text-decoration: line-through underline"` 是可以的，描述的这种组合确实没考虑

感谢，那我先用这种方式实现
