### ISSUE TITLE
大佬，会考虑支持colgroup和figure标签么

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#57]
**Describe the bug**
大佬，会考虑支持colgroup和figure标签么
**HTML content:**

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
 0.3.22

**poi-tl version:**
1.11.1

**Additional context**

**Comment by stringutils** [comment]
已经解决

**Comment by stringutils** [comment]
对于colgroup标签，我考虑的能不能还保持现状不单独不解析colgroup和col，但是在处理td的的style时，取td和col的并集样式(td优先级高)

**Comment by draco1023** [comment]
figure应该不需要处理
colgroup是可以处理的

**Comment by stringutils** [comment]
啊，我看colgroup不生效，源码中TableRenderer把colgroup的element给remove处理的
`<table  style="float:left;width:66.51%;">
		<colgroup>
			<col style="width:57.38%;">
			<col style="width:16.97%;">
			<col style="width:25.65%;">
		</colgroup>
		<tbody>
			<tr>
				<td>1</td>
				<td>1</td>
				<td>1</td>
			</tr>
			<tr>
				<td>1</td>
				<td>1</td>
				<td>1</td>
			</tr>
			<tr>
				<td>1</td>
				<td>1</td>
				<td>1</td>
			</tr>
		</tbody>
	</table>`

**Comment by stringutils** [comment]
我用最新的代码试了下，colgroup标签生效了；但是colgroup中的宽度现在还没有生效，感觉有些特殊场景比如合并单元格之类的宽度不太好计算

**Comment by draco1023** [comment]
> 我用最新的代码试了下，colgroup标签生效了；但是colgroup中的宽度现在还没有生效，感觉有些特殊场景比如合并单元格之类的宽度不太好计算 @draco1023

倒不是不好计算的问题，其实目前的计算逻辑已经足够支撑了，只是要提前合并到单元格样式。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col#attr-width 中显示`width`属性已经废弃了，试过在`col`中使用属性或者样式在浏览器中似乎都没有效果

**Comment by draco1023** [comment]
已支持，优先级：th/td style > col style > col width属性

**Comment by stringutils** [comment]
> 

666
