### ISSUE TITLE
全局字体和单个标签字体的优先级

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#59]
**Describe the bug**
对于字体的设置，如果优先级调整成  标签字体 > 全局字体，这样会有风险么
**HTML content:**

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
 0.3.22

**poi-tl version:**
1.11.1

**Additional context**

**Comment by draco1023** [comment]
全局字体设置是为了对整个html进行样式归一化而存在的，如果不需要，那么完全可以不设置，本身就会按照CSS的叠加优先级渲染；如果是想要有个兜底的全局字体/字号设置，那么可以在body上声明样式啊。

**Comment by stringutils** [comment]
> 全局字体设置是为了对整个html进行样式归一化而存在的，如果不需要，那么完全可以不设置，本身就会按照CSS的叠加优先级渲染；如果是想要有个兜底的全局字体/字号设置，那么可以在body上声明样式啊。

豁然开朗，这个思路不错；

**Comment by stringutils** [comment]
> > 全局字体设置是为了对整个html进行样式归一化而存在的，如果不需要，那么完全可以不设置，本身就会按照CSS的叠加优先级渲染；如果是想要有个兜底的全局字体/字号设置，那么可以在body上声明样式啊。
> 
> 豁然开朗，这个思路不错；

当前应该不会解析body上的属性

**Comment by stringutils** [comment]
> > > 全局字体设置是为了对整个html进行样式归一化而存在的，如果不需要，那么完全可以不设置，本身就会按照CSS的叠加优先级渲染；如果是想要有个兜底的全局字体/字号设置，那么可以在body上声明样式啊。
> > 
> > 
> > 豁然开朗，这个思路不错；
> 
> 当前应该不会解析body上的属性 @draco1023

我现在是富文本的最外层拼了一个带字体的figure标签，但是生成的word会有个换行；现在看对于figure这样的块标签应该都会换行

**Comment by draco1023** [comment]
目前确实不会解析body上的属性，因为出发点是处理html片段，而非完整的html文档。
在`0.4.0`及`0.4.0-poi5`版本中进行了一次较大的调整，你所说的块标签会引起多一个换行是可以解决的，可能需要增加一个针对`figure`的渲染器。不清楚你为何要使用`figure`标签，最好是能给出你的html代码，不要直接贴在回复框里，使用添加代码段的方式。

**Comment by stringutils** [comment]
`<figure style=\"width:35.3%;float:right\"><img src=\"https://avatars.githubusercontent.com/u/1821583?s=80&v=4 \"/></figure>`；有些富文本插件生成的html会有块元素；

**Comment by draco1023** [comment]
在`0.4.1`版本中支持了对完整html进行解析，因此可以继承的全局样式也可以用起来了（类似`background`这样的样式无效，因为在word中不存在像`html`/`body`这样的全局父容器，除非html直接渲染为整个word文档，而不是在模板中部分替换使用）。
