### ISSUE TITLE
图片后缀类型和实际类型不一致造成生成word有背景色

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#61]
**Describe the bug**
图片后缀类型和实际类型不一致造成生成word有背景色
**HTML content:**

附件是png类型的，但以jpg后缀，生成word的截图；
而且代码中获取图片的方式会不会误伤一些其他类型图片
 ```
   /**
     * 根据图片反推类型
     *
     * @param image 图片
     * @return 图片类型
     */
    protected ImageType typeOf(BufferedImage image) {
        return image.getColorModel().hasAlpha() ? ImageType.PNG : ImageType.JPG;
    }
```
**Expected behavior**

**Screenshots**
![1668077009505](https://user-images.githubusercontent.com/35484811/201070428-ece389e4-68a4-4549-901c-c3f9c139c65a.png)
**poi-tl-ext version:**
0.4.1

**poi-tl version:**
1.11.1

**Additional context**

**Comment by draco1023** [comment]
图片后缀类型和实际类型不一致的情况不属于本类库需要考虑的范围，你所列出的代码只是在匹配不到的情况下兜底用的，首先还是会按照后缀去匹配
