### ISSUE TITLE
pgMar为null的话是什么原因导致的呢

### ISSUE THREAD

**Issue by 15542688830** [draco1023/poi-tl-ext#62]
![d5459554bd361677c144bdfa0464e5a](https://user-images.githubusercontent.com/29878065/201258021-ffbbabd4-904f-44bd-8f31-4f1f0658ff1f.png)
小白实在找不到原因  还请麻烦大佬指导  之前还是可以的  我怀疑是其他工程引入的包导致冲突引起的

**Comment by draco1023** [comment]
用解压缩工具将你的word文档解压， 看看 `/word/document.xml` 中 `w:sectPr` 这个节点是否包含 `w:pgMar` 子节点，如果没有那应该是模板文档的问题，按理应该不会有完全没有边距的文档。

**Comment by 15542688830** [comment]
非常感谢 解压后还真没有

**Comment by 15542688830** [comment]
不清楚是什么原因，我用Poi-tl无模板创建文件    XWPFTemplate.create创建的文件 都没有边距 1.12版本

**Comment by stringutils** [comment]
> 不清楚是什么原因，我用Poi-tl无模板创建文件 XWPFTemplate.create创建的文件 都没有边距 1.12版本

@draco1023 大佬，这个是什么原因啊，我试过用POI动态生成word模板再生成word,就一直报这个错

**Comment by draco1023** [comment]
估计是生成的word没有给body定义页面尺寸、边距等信息，现在按照office的2010模板定义加上了默认值
