### ISSUE TITLE
有什么办法可以控制长图插入到word中全部显示吗

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#63]
**Describe the bug**
我遇到的问题是，如果插入一个长图，则在生成的word中该图片显示不全
这个是原图
![3](https://user-images.githubusercontent.com/35484811/201297685-93150b09-ea05-40c1-b8cf-179639b04f81.jpg)

**HTML content:**
```
<figure>
	<img src="http://127.0.0.1:8080/3.jpg">
</figure>
```
**Expected behavior**

**Screenshots**
![1668155200528](https://user-images.githubusercontent.com/35484811/201298152-fef50ca0-1328-4a56-b017-96b6ab253ecc.png)

**poi-tl-ext version:**
[e.g. 0.4.1]

**poi-tl version:**
[e.g. 1.11.1]

**Additional context**

**Comment by draco1023** [comment]
没想到有什么好办法，在渲染的过程中并不知道当前页剩余的高度是多少，最多只能知道一页的最大可用高度（总高度-上下边距），因此无法根据页面的可用高度以及图片的高宽比再去计算

**Comment by stringutils** [comment]
> 没想到有什么好办法，在渲染的过程中并不知道当前页剩余的高度是多少，最多只能知道一页的最大可用高度（总高度-上下边距），因此无法根据页面的可用高度以及图片的高宽比再去计算

我有个想法是：当一页没办法完全放下一个图片时，word应该会自动放到新的 一页中；在新的一页中可以用（总高度-上下边距）限制最大宽高么

**Comment by stringutils** [comment]
大概这么逻辑
![1668161167904](https://user-images.githubusercontent.com/35484811/201317213-496d5cd2-34eb-4abc-96a4-979218afafad.png)

**Comment by draco1023** [comment]
我不认为这是个好办法，你应该优先考虑在img标签上限制宽高。另外图片并不是按照块状元素渲染的，你说的重起一页的方式会使文档割裂。当然你可以按照自己的想法实现看看效果。

**Comment by baike777** [comment]
当图片宽度大于word最大值时，按比例缩小图片再插入word中。
