### ISSUE TITLE
渲染问题

### ISSUE THREAD

**Issue by white-cwy-dove** [draco1023/poi-tl-ext#67]
请问一下 为什么htmlRenderPolicy策略为什么会不按照标签顺序渲染
如:
{{one}} 使用自定义策略 继承AbstractRenderPolicy
{{two}} 使用htmlRenderPolicy策略
渲染的内容two要在one的内容之上

**Comment by draco1023** [comment]
按照
{{one}}
{{two}}
的结构试了下，one使用TextRenderPolicy，two使用HtmlRenderPolicy，没有出现顺序不对的情况，你应该看看是不是你的自定义策略的问题。另外提问题的时候请提供你的模板和数据，不然别人怎么能复现你的问题。

**Comment by white-cwy-dove** [comment]
demo 地址https://gitee.com/hx199808/test-pol-html.git

**Comment by draco1023** [comment]
> demo 地址https://gitee.com/hx199808/test-pol-html.git

访问不了

**Comment by white-cwy-dove** [comment]
> > demo 地址https://gitee.com/hx199808/test-pol-html.git
> 
> 访问不了

忘了开源了 已经可以了

**Comment by draco1023** [comment]
是你自定义的Policy的问题，添加的段落都是直接使用XWPFDocument创建的，默认就会在最后面，而不是占位符所在的位置

**Comment by white-cwy-dove** [comment]
> 是你自定义的Policy的问题，添加的段落都是直接使用XWPFDocument创建的，默认就会在最后面，而不是占位符所在的位置

好的 感谢
