### ISSUE TITLE
解析img标签失败

### ISSUE THREAD

**Issue by sikangdi** [draco1023/poi-tl-ext#71]
**Describe the bug**
解析img标签失败

**HTML content:**
<img src=\"https://xxxxxxx/help/pictures/21f68543008743319f4a634a358d18fe.png\" style=\"max-width:100%;\" contenteditable=\"false\"/>"

**Expected behavior**
希望直接在word里面展示出来图片

**Screenshots**
![image](https://github.com/draco1023/poi-tl-ext/assets/69343213/e53696df-eba7-4525-a618-00046fe4950f)

**poi-tl-ext version:**
0.4.2

**poi-tl version:**
1.10.0

**Additional context**

**Comment by draco1023** [comment]
你这是没有引用commons-io的依赖

**Comment by sikangdi** [comment]
好的，可以了，谢谢老哥

**Comment by zlp8013** [comment]
为啥图片渲染失败....
![image](https://github.com/draco1023/poi-tl-ext/assets/101457266/0a94bcca-4494-4d8b-95ad-07779324e1bb)
![image](https://github.com/draco1023/poi-tl-ext/assets/101457266/40e012b1-8f8a-44c9-b8a7-2e67f96d1d42)

**Comment by draco1023** [comment]
> 

没支持本地图片文件

**Comment by Wave-zf** [comment]
@draco1023 请问是不是不支持base64的图片显示，例：<img src="data:image/png;base64,iVBORw0KG......nZzAAAASUVORK5CYII=">

**Comment by Wave-zf** [comment]
@draco1023 @draco1023 请问是不是不支持base64的图片显示
![image](https://github.com/draco1023/poi-tl-ext/assets/33048975/92da7eeb-15f8-460c-b0db-2efb2168b2e5)

**Comment by draco1023** [comment]
> @draco1023 @draco1023 请问是不是不支持base64的图片显示 ![image](https://private-user-images.githubusercontent.com/33048975/296678135-92da7eeb-15f8-460c-b0db-2efb2168b2e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTM2NzcsIm5iZiI6MTcwNTQxMzM3NywicGF0aCI6Ii8zMzA0ODk3NS8yOTY2NzgxMzUtOTJkYTdlZWItMTVmOC00NjBjLWIwZGItMmVmYjIxNjhiMmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEzNTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjQ1ZGY5Y2Q4ZGRlMGQ1OTM3MmRhODdkNGRkMWQ0NDNhMzdhYmU2NGE1YTE1ODQ0NmUxMmUwNTIxMzJkNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7lkokpO4hPWHXXTH9kZ7UeJBFqgJwb9TowRU4JD0XMw)

@Wave-zf 支持的

**Comment by rainyuu-i** [comment]
base64的图片生成后是空白的

**Comment by rainyuu-i** [comment]
base64图片，但是word打开后是空白的
![Snipaste_2025-01-06_17-34-20](https://github.com/user-attachments/assets/ade5b0cf-8536-4af9-a0ef-6db29238f5c5)

poi-tl-ext version:
0.4.8

poi-tl version:
1.9.1

**Comment by draco1023** [comment]
> base64图片，但是word打开后是空白的 ![Snipaste_2025-01-06_17-34-20](https://private-user-images.githubusercontent.com/67689505/400378477-ade5b0cf-8536-4af9-a0ef-6db29238f5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyMzEwMTYsIm5iZiI6MTczNjIzMDcxNiwicGF0aCI6Ii82NzY4OTUwNS80MDAzNzg0NzctYWRlNWIwY2YtODUzNi00YWY5LWEwZWYtNmRiMjkyMzhmNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDA2MTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxM2ZkZmRhZGFjNjlmMjFjMjExMjVmNWYzYTQwNGJjOGFkODhjNWVhZGQ1Nzg4ZGE2NjNkZjVjMTgwODIyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C9NEORTZrgu8b0-QvfhSCqIq5wWy42MzudL3Ctc2FmA)
> 
> poi-tl-ext version: 0.4.8
> 
> poi-tl version: 1.9.1

升级版本试试，或者提供一下html内容

**Comment by rainyuu-i** [comment]
升级版本也试过了，降版本也试过

[test.txt](https://github.com/user-attachments/files/18328836/test.txt)

**Comment by rainyuu-i** [comment]
找到问题了，是XWPFDocument合并word的时候把图片弄没了
