### ISSUE TITLE
解析代码块格式失效

### ISSUE THREAD

**Issue by sikangdi** [draco1023/poi-tl-ext#72]
**Describe the bug**
解析代码块格式失效

**HTML content:**
<code class="Plain text"><xmp>//监听main.html这个iframe过来的消息
      window.addEventListener('message', ({data}) => {
        data && data.cmd == 'outer' && iframe.contentWindow.postMessage({cmd:'outer'});
        //main.html问三方平台是否嵌套开发，三方平台应答为“是”
        data && data.cmd == 'exit' && (location.href = 'index.html');
        //iframe告诉三方平台，他退出系统了，让三方平台决定是否退出
      });</xmp></code>

**Screenshots**
![image](https://github.com/draco1023/poi-tl-ext/assets/69343213/146702d3-96d9-4f25-aec1-995855d0a55a)

**poi-tl-ext version:**
0.4.2

**poi-tl version:**
1.10.0

**Comment by sikangdi** [comment]
<pre><code class="Plain text"><xmp>//监听main.html这个iframe过来的消息
      window.addEventListener('message', ({data}) => {
        data && data.cmd == 'outer' && iframe.contentWindow.postMessage({cmd:'outer'});
        //main.html问三方平台是否嵌套开发，三方平台应答为“是”
        data && data.cmd == 'exit' && (location.href = 'index.html');
        //iframe告诉三方平台，他退出系统了，让三方平台决定是否退出
      });</xmp></code></pre>   
完整代码是这样子的

**Comment by draco1023** [comment]
xmp标签从html3.2就过时了，应该用pre或者code标签代替，目前此类标签尚未支持，其中的问题跟#68有关

**Comment by draco1023** [comment]
> xmp标签从html3.2就过时了，应该用pre或者code标签代替，目前此类标签尚未支持，其中的问题跟 #68 有关。另外，代码块中的 `<` `>` `&` 字符都需要使用html转义符表示。

@sikangdi 请试试0.4.3版本。另外经过测试发现，对于`pre`标签内的内容是需要使用html转义符的，但是对于`xmp`标签是不需要转义的，请注意这个区别。

**Comment by sikangdi** [comment]
> > xmp标签从html3.2就过时了，应该用pre或者code标签代替，目前此类标签尚未支持，其中的问题跟#68有关。另外，代码块中的`<` `>` `&`字符都需要使用html转义符表示。
> 
> @sikangdi请尝试0.4.3版本。另外经过测试发现，对于`pre`标签内的内容是需要使用html转义符的，但是对于`xmp`标签是不需要转义的，请注意这个区别。

好的，感谢
