### ISSUE TITLE
支持latex公式导出word似乎不太实用

### ISSUE THREAD

**Issue by daixianjun** [draco1023/poi-tl-ext#74]
@Test
    void doRender() throws IOException {
        LaTeXRenderPolicy laTeXRenderPolicy = new LaTeXRenderPolicy();
        Configure configure = Configure.builder()
                .bind("math1", laTeXRenderPolicy)
                .bind("math2", laTeXRenderPolicy)
                .bind("math3", laTeXRenderPolicy)
                .bind("math4", laTeXRenderPolicy)
                .build();
        Map<String, Object> data = new HashMap<>(4);
        data.put("math1", "$$ x+2=3 $$");
        data.put("math2", "\\[ \\sum_{i=1}^{\\infty} \\frac{1}{n^s} \n" +
                "= \\prod_p \\frac{1}{1 - p^{-s}} \\]");
        data.put("math3", "Product $\\prod_{i=a}^{b} f(i)$ inside text. $\\mathbb{N} \\mathbf{N} \\mathbb{Z} \\mathbf{Z} \\mathbb{D} \\mathbf{D} \\mathbb{Q} \\mathbf{Q} \\mathbb{R} \\mathbf{R} \\mathbb{C} \\mathbf{C}$");
        data.put("math4", "$\\lim_{x\\to\\infty} f(x)$");
        try (InputStream inputStream = LaTeXRenderPolicyTest.class.getResourceAsStream("/math.docx")) {
            XWPFTemplate.compile(inputStream, configure).render(data).writeToFile("latex_out.docx");
        }
    }

如上面的示例代码所示（代码位置：org.ddr.poi.latex.LaTeXRenderPolicyTest），这里必须在模板规定好公式的个数， 位置。实际开发中并不知道文档中有多少个公式以及位置， 也就无法定义模板。

**Comment by draco1023** [comment]
如果按你说的“无法定义模板”，那就无法使用模板引擎，也没有必要使用本扩展，应该按照你实际的需求去寻找合适的工具。

**Comment by daixianjun** [comment]
> 如果按你说的“无法定义模板”，那就无法使用模板引擎，也没有必要使用本扩展，应该按照你实际的需求去寻找合适的工具。

不知道我说清楚我的场景与需求吗？我感觉这种场景也是常见的。

**Comment by draco1023** [comment]
> > 如果按你说的“无法定义模板”，那就无法使用模板引擎，也没有必要使用本扩展，应该按照你实际的需求去寻找合适的工具。
> 
> 不知道我说清楚我的场景与需求吗？我感觉这种场景也是常见的。

请问你觉得你自己说清楚了吗？首先请搞清楚，这是**模板引擎**`poi-tl`的扩展，你觉得无法定义模板，那就不应该使用；如果你觉得能够定义模板，请提供模板和你的数据，并描述清楚预期的呈现结果。

**Comment by daixianjun** [comment]
> 

您好：假如说我的模板是{{abstractStr}}， 对应的内容是 "清华大大学$a^2+b^2=c^2$之江实验室$\\widehat{y}$\n杭州市"
期望的输出内容是：
![image](https://github.com/draco1023/poi-tl-ext/assets/10558876/b0503021-4841-4ad9-8574-d73f7e131b69)

也就是模板的内容里包含数量不等的latex公式或者其他文本。

**Comment by daixianjun** [comment]
> 

或者说拿示例代码中的这个来说明： 
 data.put("math3", "Product $\\prod_{i=a}^{b} f(i)$ inside text. $\\mathbb{N} \\mathbf{N} \\mathbb{Z} \\mathbf{Z} \\mathbb{D} \\mathbf{D} \\mathbb{Q} \\mathbf{Q} \\mathbb{R} \\mathbf{R} \\mathbb{C} \\mathbf{C}$");
![image](https://github.com/draco1023/poi-tl-ext/assets/10558876/55517892-f102-442f-9ba2-266a530422b1)

这个表格里内容是不是应该是以Product开头的呢？

**Comment by draco1023** [comment]
这个问题已经在0.4.4以上的版本中修复了

> > 
> 
> 或者说拿示例代码中的这个来说明： data.put("math3", "Product ∏i=abf(i) inside text. NNZZDDQQRRCC"); ![image](https://github.com/draco1023/poi-tl-ext/assets/10558876/55517892-f102-442f-9ba2-266a530422b1)
> 
> 这个表格里内容是不是应该是以Product开头的呢？

**Comment by daixianjun** [comment]
> 这个问题已经在0.4.4以上的版本中修复了
> 
> > > 
> > 
> > 
> > 或者说拿示例代码中的这个来说明： data.put("math3", "Product ∏i=abf(i) inside text. NNZZDDQQRRCC"); ![image](https://user-images.githubusercontent.com/10558876/254175898-55517892-f102-442f-9ba2-266a530422b1.png)
> > 这个表格里内容是不是应该是以Product开头的呢？



> 这个问题已经在0.4.4以上的版本中修复了
> 
> > > 
> > 
> > 
> > 或者说拿示例代码中的这个来说明： data.put("math3", "Product ∏i=abf(i) inside text. NNZZDDQQRRCC"); ![image](https://user-images.githubusercontent.com/10558876/254175898-55517892-f102-442f-9ba2-266a530422b1.png)
> > 这个表格里内容是不是应该是以Product开头的呢？

好的，我看看  谢谢。

**Comment by daixianjun** [comment]
已经支持，感谢作者。

**Comment by daixianjun** [comment]
已经支持（或者说解决），感谢作者。
