### ISSUE TITLE
可以同时解析多个html到一个word，且中间还隔着其他动态内容

### ISSUE THREAD

**Issue by wangdy0909** [draco1023/poi-tl-ext#8]
可以同时解析多个html到一个word，且中间还隔着其他动态内容，也就是循环对象(User)的方式，对象有2个属性，比如标题，内容（内容为html），然后List<User>的循环插入到word里。

**Comment by draco1023** [comment]
你应该使用poi-tl自带的模板语法来进行遍历（请参考 http://deepoove.com/poi-tl/#_%E9%9D%9E%E7%A9%BA%E9%9B%86%E5%90%88），将内容的policy设置为`HtmlRenderPolicy`
