### ISSUE TITLE
请问生成的表格宽度是如何决定的?为什么我html里设置了表格的宽度但没有生效

### ISSUE THREAD

**Issue by MrXiao-9527** [draco1023/poi-tl-ext#80]
[我的html表格.txt](https://github.com/draco1023/poi-tl-ext/files/12226306/html.txt)
![image](https://github.com/draco1023/poi-tl-ext/assets/58031184/9f12d7c7-3101-4a84-9269-d8385fb4844a)
![image](https://github.com/draco1023/poi-tl-ext/assets/58031184/0528f09a-57fb-4ed2-957f-4d83f4ec8084)

**Comment by draco1023** [comment]
word并不像html中一样表格是可以有无限宽度的，最大也就是页面可编辑宽度，像素单位也很难在二者中对齐，建议全部使用百分比，另外从你的html来看，定义的`col`是无效的，需要用`colgroup`包起来
