### ISSUE TITLE
请问如何自定义h1~h6标题的html转化

### ISSUE THREAD

**Issue by HYliangkai** [draco1023/poi-tl-ext#81]
大佬请问一下如何自定义h1到h6的html标签转化成对应的标题1到标题6啊
不管h1-h6的css样式,只要有h1-h6,统一转化对应的标题
现在存在的问题是pot-tl的目录生成插件要有标题才能生成目录,但是html转化的标题只是“正文”并不是“标题”
QAQ

**Comment by HYliangkai** [comment]
已解决问题

**Comment by 309026159** [comment]
请问怎么解决的呢

**Comment by 309026159** [comment]
@HYliangkai

**Comment by 309026159** [comment]
@draco1023
