### ISSUE TITLE
是否支持富文本中视频导出，目前视频导出为空。

### ISSUE THREAD

**Issue by dch1314** [draco1023/poi-tl-ext#84]
**Describe the bug**

**HTML content:**
<p>Some html content to reproduce the issue</p>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.3.12]

**poi-tl version:**
[e.g. 1.9.1]

**Additional context**

**Comment by draco1023** [comment]
不支持，一方面word文档并不适宜查看视频，仅能以嵌入对象的方式外部打开，另一方面html中的视频除非是直接提供文件地址的，否则并不容易下载。
