### ISSUE TITLE
div标签解析生成word为什么会有空行

### ISSUE THREAD

**Issue by HYliangkai** [draco1023/poi-tl-ext#85]
**Describe the bug**
如题,使用div标签解析出来的word会在段落的前面产生一段空行,而将div改成span之后就没有空行了  
请问是什么原因导致的?
<img width="1101" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/a117d5b5-fe64-40ca-a464-6245b69cecac">
<img width="1223" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/f2db0400-8fc9-41e1-b64f-de585a8b1e78">
<img width="906" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/fdd5c8c6-6cd9-4d78-9f1d-ab8ade71e191">
<img width="1190" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/5305d503-e156-4898-98b6-aab38408aced">
求回答
**poi-tl-ext version:**
0.4.5

**poi-tl version:**
1.10.5

**Comment by draco1023** [comment]
在html中div是块状元素，span是行内元素，所以出现了这种情况，在word中段落和段落不存在嵌套的情况，我会考虑下如何避免这种不必要的换行
