### ISSUE TITLE
富文本编辑当中有表格样式不生效

### ISSUE THREAD

**Issue by jwz1218626201** [draco1023/poi-tl-ext#86]
**Describe the bug**
表格的样式已经是行内样式，但是没有生效

**HTML content:**
<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><th><span style=\"font-weight: normal;\">11</span></th><th><span style=\"font-weight: normal;\">12</span></th><th><span style=\"font-weight: normal;\">22</span></th><th><span style=\"font-weight: normal;\">33</span></th><th><span style=\"font-weight: normal;\">44</span></th></tr><tr><td>1</td><td>2</td><td>232</td><td>2223</td><td>223</td></tr><tr><td>12</td><td>21</td><td>2323</td><td>2323</td><td>232</td></tr><tr><td>13</td><td>23</td><td>323232</td><td>2323</td><td>232</td></tr><tr><td>14</td><td>23</td><td>2232</td><td>232</td><td>22323</td></tr></tbody></table>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
0.4.6

**poi-tl version:**
1.10.5

**Additional context**

**Comment by jwz1218626201** [comment]
<table border=\"0\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><th><span style=\"font-weight: normal;\">11</span></th><th><span style=\"font-weight: normal;\">12</span></th><th><span style=\"font-weight: normal;\">22</span></th><th><span style=\"font-weight: normal;\">33</span></th><th><span style=\"font-weight: normal;\">44</span></th></tr><tr><td>1</td><td>2</td><td>232</td><td>2223</td><td>223</td></tr><tr><td>12</td><td>21</td><td>2323</td><td>2323</td><td>232</td></tr><tr><td>13</td><td>23</td><td>323232</td><td>2323</td><td>232</td></tr><tr><td>14</td><td>23</td><td>2232</td><td>232</td><td>22323</td></tr></tbody></table>

表格头的字体样式似乎没生效

**Comment by draco1023** [comment]
所以你预期的是表头不加粗？但是你有没有发现这个html在浏览器里打开也是加粗的

**Comment by draco1023** [comment]
我没看出有什么问题，你试试0.4.7版本呢
