### ISSUE TITLE
解析块级标签的时候，不换行显示

### ISSUE THREAD

**Issue by zlp8013** [draco1023/poi-tl-ext#87]
比如：解析age标签中的<p></p>的时候，不换行显示，而是显示在name标签的后面，有没有什么办法可以实现
![image](https://github.com/draco1023/poi-tl-ext/assets/101457266/fb401437-77a7-46d6-8360-eb584cf75faf)
![image](https://github.com/draco1023/poi-tl-ext/assets/101457266/e80773fd-55ef-48df-8979-c32caf37b0f4)
![image](https://github.com/draco1023/poi-tl-ext/assets/101457266/f24e8a23-b711-47a4-8cbc-192d815c05ef)

**Comment by draco1023** [comment]
这是因为你的age用了p标签，如果使用行内标签是没问题的
