### ISSUE TITLE
关于使用div标签生成的word会有空行问题--续

### ISSUE THREAD

**Issue by HYliangkai** [draco1023/poi-tl-ext#88]
[续问题85](https://github.com/draco1023/poi-tl-ext/issues/85),使用了最新版本的poi-ti-ext(0.4.7),生成的word依旧会有按照div的数量形成空行的情况
<img width="1082" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/94a11c2d-c3ef-4071-8f3a-d5fc0f39f6ae">
<img width="836" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/f65aec53-cc97-45ee-affd-9cc8e1032f83">
请问一下是什么原因导致的啊...

**Comment by draco1023** [comment]
一部提供html内容，二不提供你的模板，让别人瞎猜？

**Comment by HYliangkai** [comment]
作者您好,以下是测试内容
## html内容
1. 使用div作为嵌套
```html
<div>
<div>
<p style="font-size: 12pt;"><span style="font-size: 14pt;">标题1</span></p>
<p style="text-align: center;">嵌套模板模板嵌套</p>
<p style="font-size: 12pt; text-align: center;">测试文段文段测试</p>
</div>
</div>
```
2.使用span作为嵌套
```html
<span>
<span>
<p style="font-size: 12pt;"><span style="font-size: 14pt;">标题1</span></p>
<p style="text-align: center;">嵌套模板模板嵌套</p>
<p style="font-size: 12pt; text-align: center;">测试文段文段测试</p>
</span>
</span>
```
## 模板
将{{content}}内容进行替换
<img width="1128" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/72b45890-cb92-410e-88e0-d9ba9b9ea596">
## 生成结果
1. 使用div作为嵌套生成的结果
<img width="995" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/3cee0c35-5407-4833-95f3-81bb46a00da6">
2. 使用span作为嵌套生成的结果
<img width="1000" alt="image" src="https://github.com/draco1023/poi-tl-ext/assets/56477361/26dda669-41b9-4142-8068-955d992076f9">

**Comment by draco1023** [comment]
按照你的内容和模板没复现出来

**Comment by HYliangkai** [comment]
最后还是用span替代div了....
