### ISSUE TITLE
表格中的富文本无法被解析

### ISSUE THREAD

**Issue by zlp8013** [draco1023/poi-tl-ext#89]
这是之前在poi-tl提出的lssues:
https://github.com/Sayi/poi-tl/issues/1038

普通表格无所谓，给对应的字段绑定HtmlRenderPolicy就可以，但是问题就在于，现在是自定义表格渲染策略，这时候再为对应字段绑定HtmlRenderPolicy就会失效，不会解析，请问有什么办法解决吗，我看poi-tl的大佬回复，好像没法弄，也可能是我没懂

**Comment by draco1023** [comment]
建议你用自定义的合并逻辑直接生成完整的html，然后直接用富文本渲染整个表格
