### ISSUE TITLE
存在安全漏洞

### ISSUE THREAD

**Issue by 309026159** [draco1023/poi-tl-ext#90]
![image](https://github.com/draco1023/poi-tl-ext/assets/139694746/18d51722-3a0c-474a-b683-3cce182bd852)

**Comment by 309026159** [comment]
<dependency>
            <groupId>io.github.draco1023</groupId>
            <artifactId>poi-tl-ext</artifactId>
            <version>0.4.7-poi5</version>
</dependency>

**Comment by draco1023** [comment]
@309026159  Thanks for reporting. 0.4.8 version released.

**Comment by 309026159** [comment]
> @309026159 感谢您的报告。0.4.8版本发布。

目前来看1.9.0的poi-tl没有提示存在安全问题，仅供参考
