### ISSUE TITLE
请问如何将h1标签渲染成word的标题1，目前h1会变成word正文

### ISSUE THREAD

**Issue by 309026159** [draco1023/poi-tl-ext#91]
**Describe the bug**

**HTML content:**
<p>Some html content to reproduce the issue</p>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.3.12]

**poi-tl version:**
[e.g. 1.9.1]

**Additional context**

**Comment by draco1023** [comment]
请参考 #49 
Word里的标题1等其实只是一组样式的集合，对于同一种标题样式都是一样的，但是对于HTML来说，同样是h1标签却是可以有不同的样式的，所以并不能简单地将二者进行对应，目前的处理方式是会按照CSS来进行样式转换，但是会对这些转换后的标签设置大纲等级，是可以从大纲目录中看出来的。
