### ISSUE TITLE
导出table时样式丢失，实际上的样式实在tr里面

### ISSUE THREAD

**Issue by JionDack** [draco1023/poi-tl-ext#96]
**Describe the bug**
版本0.4.8
**HTML content:**
<p>Some html content to reproduce the issue</p>
<table data-sort="sortDisabled" align="center">
    <tbody>
        <tr class="firstRow">
            <td width="111" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid; background-color: rgb(170, 170, 170);" align="center">
                维度
            </td>
            <td valign="middle" rowspan="1" colspan="2" style="word-break: break-all; border-width: 1px; border-style: solid; background-color: rgb(170, 170, 170);" align="center" width="1360">
                情况记录<br/>
            </td>
        </tr><tr>
            <td width="155" valign="middle" rowspan="3" colspan="1" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                A2-办园条件
            </td>
            <td width="204" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                亮点推荐
            </td>
            <td width="1829" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr>
        <tr>
            <td width="337" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                问题诊断
            </td>
            <td width="1123" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr>
        <tr>
            <td width="337" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                提升空间
            </td>
            <td width="1123" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr><tr>
            <td width="155" valign="middle" rowspan="3" colspan="1" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                A4-保育与安全
            </td>
            <td width="204" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                亮点推荐
            </td>
            <td width="1829" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr>
        <tr>
            <td width="337" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                问题诊断
            </td>
            <td width="1123" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr>
        <tr>
            <td width="337" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="center">
                提升空间
            </td>
            <td width="1123" valign="middle" style="word-break: break-all; border-width: 1px; border-style: solid;" align="left">
            </td>
        </tr>    </tbody>
</table>
**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
[e.g. 0.4.8]

**poi-tl version:**
[e.g. 1.10.0]

**Additional context**
在使用的时候发现样式并没生效

**Comment by JionDack** [comment]
111

**Comment by draco1023** [comment]
请使用markdown里的代码段来提交html内容，并提供预期的结果图，如果你是指tr标签上的`class`没生效的话，那确实是这样的，目前只会处理style里的样式

**Comment by JionDack** [comment]
是的，但是固定高宽的话好像没起作用是没法设置吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月17日 09:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [draco1023/poi-tl-ext] 导出table时样式丢失，实际上的样式实在tr里面 (Issue #96) |

请使用markdown里的代码段来提交html内容，并提供预期的结果图，如果你是指tr标签上的class没生效的话，那确实是这样的，目前只会处理style里的样式

**Comment by draco1023** [comment]
推荐在colgroup中定义各列的宽度，而不是在每个td上，如果一定要在td上定义可以写在style里，不支持width属性
