### ISSUE TITLE
富文本过大或文本中图片过大时导出失败

### ISSUE THREAD

**Issue by sikangdi** [draco1023/poi-tl-ext#97]
**Describe the bug**
富文本内容太多，或者富文本里包含的图片过大时报错，导出失败

**HTML content:**

**Expected behavior**
希望文本过大时能顺利导出

**Screenshots**
![image](https://github.com/draco1023/poi-tl-ext/assets/69343213/54d2a092-5088-497b-a567-77e6e70c9319)

**poi-tl-ext version:**
0.4.2

**poi-tl version:**
1.10.0

**Comment by sikangdi** [comment]
追加报错原因
![image](https://github.com/draco1023/poi-tl-ext/assets/69343213/468fc28d-c810-490a-b779-6c75ebc339fb)

**Comment by draco1023** [comment]
事实上是poi的限制，你在执行前加一行`ZipSecureFile.setMinInflateRatio(0);`就好了

**Comment by sikangdi** [comment]
好的，感谢！
