### ISSUE TITLE
麻烦增加一个支持mathml2格式插入docx 

### ISSUE THREAD

**Issue by jaweyhuang** [draco1023/poi-tl-ext#98]
**增加原因**
有些公式被大括号包着，只有mathml无法达到预期
如使用mathml 效果如下
![Snipaste_2023-12-18_17-09-05](https://github.com/draco1023/poi-tl-ext/assets/2859115/3b2f7617-b93c-49cd-bd3a-b4810d6ad71f)
而预期效果
![Snipaste_2023-12-18_17-09-13](https://github.com/draco1023/poi-tl-ext/assets/2859115/ac7ffb38-85b1-4753-aee2-426d65b6ccda)

**现有功能不满足的原因**
由于mathml 和mathml的块不同 导致mathml2格式无法插入 现在的功能只支持mathml 无法对matml2格式进行处理

**mathml格式**
![Snipaste_2023-12-18_17-16-34](https://github.com/draco1023/poi-tl-ext/assets/2859115/0a6cc053-2cc7-497b-82af-f019612ac909)

**mathml2格式**
![Snipaste_2023-12-18_17-17-33](https://github.com/draco1023/poi-tl-ext/assets/2859115/ce0b75f1-abe4-43c3-8ce5-0b892f630306)

**处理方式**
增加类似MathMLRenderPolicy的功能
在validate方式中判断支持mml:math即可

**希望能帮忙增加一下**

**Comment by draco1023** [comment]
我不太了解mathml2，但是从你提供的信息中，`mfenced`本身就是个已经淘汰的标签，绝大多数浏览器都不支持，推荐还是用`mrow`和`mo`来编写

**Comment by jaweyhuang** [comment]
@draco1023 感谢你的回复。 是这样的， mathml2直接从docx的公式中复制出来，带有标签是mml:math，现在的MathMLRenderPolicy中验证标签是math，这样就会导致，插入的mathml2的公式数据就会为空，麻烦看看能不能增加一个对mml:math标签的支持，这是mathml2的相关信息[https://www.w3.org/TR/MathML2/](https://www.w3.org/TR/MathML2/)

**Comment by draco1023** [comment]
@jaweyhuang 这种你可以自定义一个RenderPolicy，你应该注意到之所以是`mml:math`是因为该元素上定义了`xmlns:mml`，而这个命名空间的名称可以是任意值，将这个值写死是不合适的
